import { Patient } from '../interfaces/patient';

export const PATIENTS: Patient[] = [
  {
    id: 1,
    siteId: 2,
    enterprisePatientId: 'P1234',
    medicalRecordNumber: 'M1234',
    accountNumber: 'A1234',
    firstName: 'Tony',
    lastName: 'Stark',
    middleName: 'Edward',
    nameSuffix: 'Sr.',
    age: 56,
    ageUnits: 'Y',
    gender: 'M',
    complaint: 'Headache',
    dateOfBirth: '1970-05-17',
    roomBedCode: '08',
    wardCode: 'ED',
    departmentCode: 'ED',
    urgency: '02',
    urgencyColor: 'R',
    nameAlert: '1',
    withdrawConsent: '1',
    heightInCm: 187.25,
    weightInKg: 90.71,
    vsDateTime: '2019-10-01T00:00:00',
    vsBloodPressureIndicator: '0',
    vsSystolic: '120',
    vsDiastolic: '80',
    vsPulseIndicator: '1',
    vsPulse: '80',
    vsMapLevel: '0',
    vsMap: '100',
    vsRespiratoryIndicator: '0',
    vsRespiratory: '48',
    vsTemperatureIndicator: '0',
    vsTemperature: '98.6',
    vsEndTidalLevel: '2',
    vsEndTidal: '20',
    vsOxygenSaturationIndicator: '0',
    vsOxygenSaturation: '99 on Room Air',
    vsPainScaleIndicator: '0',
    vsPainScale: '2',
    customIndicators: [
      {
        position: 0,
        code: 'Hero',
        type: 'BAT',
        description: 'JLA ID: Cuz I am Batman',
        imageName: 'batman.gif',
      },
      {
        position: 1,
        code: 'STOP',
        type: 'STOP',
        description: 'Need to Register: Stop',
        imageName: 'stop3.gif',
      },
    ],
  },
];
