import { Patient } from '../interfaces/patient';

export const PATIENTS: Patient[] = [
  {
    id: 1,
    active: true,
    siteId: 18,
    personNumber: 'P1234',
    medicalRecordNumber: 'M1234',
    accountNumber: 'A1234',
    customNumber: 'C1234',
    firstName: 'Franklin',
    lastName: 'Smith',
    middleName: 'Edward',
    nameSuffix: 'Sr.',
    fullName: 'Franklin Edward Smith, Sr.',
    age: 50,
    ageUnits: 'years',
    gender: 'M',
    complaint: 'Headache',
    birthDate: '05/17/1970',
    dateOfBirth: '1970-05-17T00:00:00',
    roomBedCode: '08',
    patientImageSrc: '../../assets/img/mock_patient_image.jpg',
    wardCode: 'ED',
    departmentCode: 'ED',
    urgency: 'R',
    urgencyColor: '#FF0000',
    nameAlert: true,
    withdrawConsent: true,
    heightInCm: 187.25,
    weightInKg: 90.71,
    vsDatetime: '2019-10-01T00:00:00',
    vsDatetimeDate: '2019-10-01',
    vsDatetimeTime: '00:00:00',
    vsBloodPressureIndicator: '1',
    vsSystolic: '120',
    vsDiastolic: '80',
    vsPulseIndicator: '1',
    vsPulse: '80',
    vsMapLevel: '0',
    vsMap: '48',
    vsRespiratoryIndicator: '0',
    vsRespiratory: '10',
    vsTemperatureIndicator: '1',
    vsTemperature: '98.6',
    vsEndTidalLevel: '2',
    vsEndTidal: '50',
    vsOxygenSaturationIndicator: '1',
    vsOxygenSaturation: '99 on Room Air',
    vsPainScaleIndicator: '0',
    vsPainScale: '2',
    visitStartDateTime: '2019-10-01T05:55:04-05:00',
    site: {
      id: 18,
      name: 'Middle Earth',
      active: true,
      timeZoneName: 'Central Standard Time',
    },
    patientIndicators: [
      {
        code: 'Hero',
        description: 'JLA ID: Cuz I am Batman',
        id: 1,
        imageName: 'batman.gif',
        imageSrc: '../../../assets/img/batman.gif',
        ordinalPosition: 0,
        patientId: 1234,
        type: 'BAT',
      },
      {
        code: 'STOP',
        description: 'Need to Register: Stop',
        id: 1,
        imageName: 'stop3.jpg',
        imageSrc: '../../../assets/img/stop3.jpg',
        ordinalPosition: 1,
        patientId: 1234,
        type: 'STOP',
      },
    ],
    patientAllergies: [
      {
        actionStatus: '',
        allergyDrugId: '',
        alternateName: '',
        comment: 'Mild Allergy',
        drugId: '',
        id: 1,
        informationSource: 'PulseCheck',
        informationSourceCode: 'PC',
        internalDrugId: '',
        isActive: true,
        name: 'Amoxicillin',
        ndc: '',
        parentDrugId: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: 'Rash',
        schedule: '',
        severity: 'Mild',
      },
      {
        actionStatus: '',
        allergyDrugId: '',
        alternateName: '',
        comment: 'Stay away from dander',
        drugId: '',
        id: 2,
        informationSource: 'PulseCheck',
        informationSourceCode: 'PC',
        internalDrugId: '',
        isActive: true,
        name: 'Pet Dander',
        ndc: '',
        parentDrugId: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: 'Sneezing',
        schedule: '',
        severity: 'Moderate',
      },
      {
        actionStatus: '',
        allergyDrugId: '',
        alternateName: '',
        comment: 'Get an allergen filter',
        drugId: '',
        id: 3,
        informationSource: 'PulseCheck',
        informationSourceCode: 'PC',
        internalDrugId: '',
        isActive: true,
        name: 'Dust Mites',
        ndc: '',
        parentDrugId: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: 'Runny Nose',
        schedule: '',
        severity: 'Mild',
      },
      {
        actionStatus: '',
        allergyDrugId: '',
        alternateName: '',
        comment: '',
        drugId: '',
        id: 4,
        informationSource: 'PulseCheck',
        informationSourceCode: 'PC',
        internalDrugId: '',
        isActive: true,
        name: 'Pollen',
        ndc: '',
        parentDrugId: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: 'Watery Eyes',
        schedule: '',
        severity: 'High',
      },
      {
        actionStatus: '',
        allergyDrugId: '',
        alternateName: '',
        comment: 'Get treatment',
        drugId: '',
        id: 5,
        informationSource: 'PulseCheck',
        informationSourceCode: 'PC',
        internalDrugId: '',
        isActive: true,
        name: 'Bee Sting',
        ndc: '',
        parentDrugId: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: 'Hives',
        schedule: '',
        severity: 'Moderate',
      },
    ],
    homeMedications: [
      {
        alternateName: '',
        category: '',
        class: '',
        comment: 'Taken as needed',
        dose: 200,
        drugId: '',
        id: 1,
        internalDrugId: '',
        isActive: true,
        lastTaken: '2020-07-12T14:30:00',
        medicationDrugId: '',
        medicationRoute: {
          id: 5,
          siteId: 1,
          routeName: 'Oral',
          pointInTime: false,
        },
        medicationUnit: {
          id: 1,
          siteId: 1,
          code: 'MG',
          unitName: 'milligrams',
          printName: 'Milligrams',
          active: true,
        },
        name: 'Tylenol',
        ndc: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: '',
        schedule: 'PRN',
        severity: '',
      },
      {
        alternateName: '',
        category: '',
        class: '',
        comment: 'Taken as needed to supplement Tylenol',
        dose: 400,
        drugId: '',
        id: 2,
        internalDrugId: '',
        isActive: true,
        lastTaken: '2020-07-11T08:00:00',
        medicationDrugId: '',
        medicationRoute: {
          id: 5,
          siteId: 1,
          routeName: 'Oral',
          pointInTime: false,
        },
        medicationUnit: {
          id: 1,
          siteId: 1,
          code: 'MG',
          unitName: 'milligrams',
          printName: 'Milligrams',
          active: true,
        },
        name: 'Motrin',
        ndc: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: '',
        schedule: 'PRN',
        severity: '',
      },
      {
        alternateName: '',
        category: '',
        class: '',
        comment: 'Take every 8 hours',
        dose: 500,
        drugId: '',
        id: 3,
        internalDrugId: '',
        isActive: true,
        lastTaken: '2020-07-12T19:30:00',
        medicationDrugId: '',
        medicationRoute: {
          id: 5,
          siteId: 1,
          routeName: 'Oral',
          pointInTime: false,
        },
        medicationUnit: {
          id: 1,
          siteId: 1,
          code: 'MG',
          unitName: 'milligrams',
          printName: 'Milligrams',
          active: true,
        },
        name: 'Azithromycin',
        ndc: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: '',
        schedule: 'Every 8 hours',
        severity: '',
      },
      {
        alternateName: '',
        category: '',
        class: '',
        comment: 'For Hypertension',
        dose: 20,
        drugId: '',
        id: 4,
        internalDrugId: '',
        isActive: true,
        lastTaken: '2020-07-13T07:30:00',
        medicationDrugId: '',
        medicationRoute: {
          id: 5,
          siteId: 1,
          routeName: 'Oral',
          pointInTime: false,
        },
        medicationUnit: {
          id: 1,
          siteId: 1,
          code: 'MG',
          unitName: 'milligrams',
          printName: 'Milligrams',
          active: true,
        },
        name: 'Lisinopril',
        ndc: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: '',
        schedule: 'Every 6 hours',
        severity: '',
      },
      {
        alternateName: '',
        category: '',
        class: '',
        comment: 'For Cholesterol Management and Monitoring',
        dose: 10,
        drugId: '',
        id: 5,
        internalDrugId: '',
        isActive: true,
        lastTaken: '2020-07-12T18:00:00',
        medicationDrugId: '',
        medicationRoute: {
          id: 5,
          siteId: 1,
          routeName: 'Oral',
          pointInTime: false,
        },
        medicationUnit: {
          id: 1,
          siteId: 1,
          code: 'MG',
          unitName: 'milligrams',
          printName: 'Milligrams',
          active: true,
        },
        name: 'Crestor',
        ndc: '',
        parentDrugName: '',
        patientId: 1234,
        reaction: '',
        schedule: 'Every 12 hours',
        severity: '',
      },
    ],
  },
];
