CREATE LOGIN [emarapiuser] WITH PASSWORD=N'emarapiuser', DEFAULT_DATABASE=[emar], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [emarapiuser]
GO
