print 'create procedure [dbo].[export_ibex_patient_allergies];';

drop procedure if exists [dbo].[export_ibex_patient_allergies];

set @template = N'
create or alter procedure [dbo].[export_ibex_patient_allergies]
as
    begin

        with cte_person
             as (select [patients].[ibex]
                      , [source].[site]
                      , [source].[person]
                      , [source].[acctnum]
                 from     [<@export_database_name>].[dbo].[hie_alg] as [source]
                          inner join [<@export_database_name>].[dbo].[pat] as [patients] on [patients].[site] = [source].[site]
                                                                         and [patients].[person] = [source].[person]
                                                                         and [patients].[acctnum] = [source].[acctnum]
                 where   [source].[person] > ''''
                         or [source].[acctnum] > ''''
                 union
                 select [patients].[ibex]
                      , [source].[site]
                      , [source].[person]
                      , [source].[acctnum]
                 from     [<@export_database_name>].[dbo].[hie_alg] as [source]
                          inner join [<@export_database_name>].[dbo].[pat] as [patients] on [patients].[site] = [source].[site]
                                                                         and [patients].[person] = [source].[person]
                 where   [source].[person] > ''''
                         and [source].[acctnum] = ''''
                 union
                 select [patients].[ibex]
                      , [source].[site]
                      , [source].[person]
                      , [source].[acctnum]
                 from   [<@export_database_name>].[dbo].[hie_alg] as [source]
                        inner join [<@export_database_name>].[dbo].[pat] as [patients] on [patients].[site] = [source].[site]
                                                                       and [patients].[acctnum] = [source].[acctnum]
                 where  [source].[person] = ''''
                        and [source].[acctnum] > ''''),
             cte_hie
             as (select cast([source].[site] as varchar(5)) + ''|'' + [patients].[ibex] as [patient_id]
                      , ltrim(rtrim([source].[class])) as                                [class]
                      , ltrim(rtrim([source].[cat])) as                                  [category]
                      , ltrim(rtrim([source].[drug])) as                                 [internal_drug_id]
                      , ltrim(rtrim([source].[ndc])) as                                  [ndc]
                      , isnull(cast([ndc].[medid] as varchar(25)), '''') as                [drug_id]
                      , ltrim(rtrim([source].[name])) as                                 [name]
                      , ltrim(rtrim('''')) as                                              [alternate__name]
                      , ltrim(rtrim([source].[alg_drug_id])) as                          [allergy_drug_id]
                      , case
                            when ltrim(rtrim([source].[status])) = ''A''
                                then 1
                            else 0
                        end as                                                           [is_active]
                      , ltrim(rtrim([source].[comment])) as                              [comment]
                      , ltrim(rtrim('''')) as                                              [schedule]
                      , ltrim(rtrim('''')) as                                              [reaction]
                      , ltrim(rtrim([source].[severity])) as                             [severity]
                      , ltrim(rtrim([source].[source])) as                               [source]
                      , ltrim(rtrim('''')) as                                              [parent_drug_id]
                      , ltrim(rtrim('''')) as                                              [parent_drug_name]
                      , ltrim(rtrim('''')) as                                              [add_user_id]
                      , ltrim(rtrim('''')) as                                              [add_datetime]
                      , ltrim(rtrim('''')) as                                              [change_user_id]
                      , ltrim(rtrim('''')) as                                              [change_datetime]
                      , ltrim(rtrim([source].[actionstatus])) as                         [action_status]
                      , ltrim(rtrim(''hie_alg'')) as                                       [information_source]
                      , ltrim(rtrim([patients].[person])) as                             [person_number]
                      , ltrim(rtrim([patients].[acctnum])) as                            [account_number]
                      , [patients].[ibex]
                      , [source].[site]
                 from   [<@export_database_name>].[dbo].[hie_alg] as [source]
                        inner join [cte_person] as [patients] on [patients].[person] = [source].[person]
                                                                 and [patients].[acctnum] = [source].[acctnum]
                        left join [<@export_database_name>].[dbo].[fdb_ndc_info] as [ndc] on [ndc].[ndc] = [source].[ndc]),
             cte_pat
             as (select cast([source].[site] as varchar(5)) + ''|'' + [source].[ibex] as [patient_id]
                      , ltrim(rtrim([source].[class])) as                              [class]
                      , ltrim(rtrim([source].[cat])) as                                [category]
                      , ltrim(rtrim([source].[drug])) as                               [internal_drug_id]
                      , ltrim(rtrim([source].[ndc])) as                                [ndc]
                      , isnull(cast([ndc].[medid] as varchar(25)), '''') as              [drug_id]
                      , ltrim(rtrim([source].[name])) as                               [name]
                      , ltrim(rtrim([source].[alt_name])) as                           [alternate__name]
                      , ltrim(rtrim([source].[alg_drug_id])) as                        [allergy_drug_id]
                      , case
                            when ltrim(rtrim([source].[status])) = ''A''
                                then 1
                            else 0
                        end as                                                         [is_active]
                      , ltrim(rtrim([source].[cmt])) as                                [comment]
                      , ltrim(rtrim([source].[sched])) as                              [schedule]
                      , ltrim(rtrim([source].[reaction])) as                           [reaction]
                      , ltrim(rtrim([source].[severity])) as                           [severity]
                      , ltrim(rtrim([source].[source])) as                             [source]
                      , ltrim(rtrim([source].[parent_id])) as                          [parent_drug_id]
                      , ltrim(rtrim([source].[parent_name])) as                        [parent_drug_name]
                      , ltrim(rtrim([source].[usr])) as                                [add_user_id]
                      , ltrim(rtrim([source].[dateadd])) as                            [add_datetime]
                      , ltrim(rtrim([source].[usrchg])) as                             [change_user_id]
                      , ltrim(rtrim([source].[datechg])) as                            [change_datetime]
                      , ltrim(rtrim([source].[actionstatus])) as                       [action_status]
                      , ltrim(rtrim([source].[provider])) as                           [information_source]
                      , ltrim(rtrim([patients].[person])) as                           [person_number]
                      , ltrim(rtrim([patients].[acctnum])) as                          [account_number]
                      , [source].[ibex]
                      , [source].[site]
                 from   [<@export_database_name>].[dbo].[alg] as [source]
                        inner join [<@export_database_name>].[dbo].[org] as [sites] on [sites].[site] = [source].[site]
                        inner join [<@export_database_name>].[dbo].[pat] as [patients] on [patients].[site] = [source].[site]
                                                                       and [patients].[ibex] = [source].[ibex]
                        left join [<@export_database_name>].[dbo].[fdb_ndc_info] as [ndc] on [ndc].[ndc] = [source].[ndc]
                 where  [source].[type] = ''A'')
             select [result].[patient_id]
                  , [result].[class]
                  , [result].[category]
                  , [result].[internal_drug_id]
                  , [result].[ndc]
                  , [result].[drug_id]
                  , [result].[name]
                  , [result].[alternate__name]
                  , [result].[allergy_drug_id]
                  , [result].[is_active]
                  , [result].[comment]
                  , [result].[schedule]
--                  , isnull([rec].[misc2],[result].[reaction]) [reaction]
--                  , isnull([sev].[misc2],[result].[severity]) [severity]
                  , [rec].[misc2] [reaction]
                  , [sev].[misc2] [severity]
                  , [src].[misc2] [source]
                  , [result].[parent_drug_id]
                  , [result].[parent_drug_name]
                  , [result].[add_user_id]
                  , [result].[add_datetime]
                  , [result].[change_user_id]
                  , [result].[change_datetime]
                  , [result].[action_status]
                  , [result].[information_source]
                  , [result].[person_number]
                  , [result].[account_number]
             from
             (
                 select [hie].[patient_id]
                      , [hie].[class]
                      , [hie].[category]
                      , [hie].[internal_drug_id]
                      , [hie].[ndc]
                      , [hie].[drug_id]
                      , [hie].[name]
                      , [hie].[alternate__name]
                      , [hie].[allergy_drug_id]
                      , [hie].[is_active]
                      , [hie].[comment]
                      , [hie].[schedule]
                      , [hie].[reaction]
                      , [hie].[severity]
                      , [hie].[source]
                      , [hie].[parent_drug_id]
                      , [hie].[parent_drug_name]
                      , [hie].[add_user_id]
                      , [hie].[add_datetime]
                      , [hie].[change_user_id]
                      , [hie].[change_datetime]
                      , [hie].[action_status]
                      , [hie].[information_source]
                      , [hie].[person_number]
                      , [hie].[account_number]
                      , [hie].[ibex]
                      , [hie].[site]
                 from     [cte_hie] as [hie]
                 union
                 select [pat].[patient_id]
                      , [pat].[class]
                      , [pat].[category]
                      , [pat].[internal_drug_id]
                      , [pat].[ndc]
                      , [pat].[drug_id]
                      , [pat].[name]
                      , [pat].[alternate__name]
                      , [pat].[allergy_drug_id]
                      , [pat].[is_active]
                      , [pat].[comment]
                      , [pat].[schedule]
                      , [pat].[reaction]
                      , [pat].[severity]
                      , [pat].[source]
                      , [pat].[parent_drug_id]
                      , [pat].[parent_drug_name]
                      , [pat].[add_user_id]
                      , [pat].[add_datetime]
                      , [pat].[change_user_id]
                      , [pat].[change_datetime]
                      , [pat].[action_status]
                      , [pat].[information_source]
                      , [pat].[person_number]
                      , [pat].[account_number]
                      , [pat].[ibex]
                      , [pat].[site]
                 from   [cte_pat] as [pat]
             ) as [result]
             join [<@export_database_name>].[dbo].[org] [o] on [result].[site] = [o].[site]
             left join [<@export_database_name>].[dbo].[idx] [rec] on [result].[reaction]=[rec].[id] and [rec].type=''LQ'' and [rec].[site]=[o].[algreactioncs]
             left join [<@export_database_name>].[dbo].[idx] [sev] on [result].[severity]=[sev].[id] and [sev].type=''LR'' and [sev].[site]=[o].[algseveritycs]
             left join [<@export_database_name>].[dbo].[idx] [src] on [result].[source]=[src].[id] and [src].type=''LS'' and [src].[site]=[o].[algsourcecs]
             order by [ibex]
                    , [add_datetime]
                    , [name]
                    , [parent_drug_name];
    end;
';

set @sql_cmd = @template;
set @sql_cmd = replace(@sql_cmd, '<@export_database_name>', @export_database_name);

exec [dbo].[sp_executesql] 
    @statement = @sql_cmd;
