[General]
Cycle=2M
Resend_interval=4H
Subject=eMAR orders requiring verification at [Site.Name]
; Must separate email recipients with commas since semi-colons are treated as comments
; This is the default list. Site-specific lists can be defined by appending _SiteId to the key. For example, Recipient_2 would specify recipients for site 2.
Recipient=rursua@pulsechecked.com
Sender=cclarkson@harriscomputer.com
SMTP_server_address=mail.harriscomputer.com
SMTP_server_port=25
SMTP_server_username=
; use base64 encoding for password - originally 'Harris4ever!'
SMTP_server_password=
; Specify whether server uses secure connections [Y/N]
SMTP_server_use_ssl=N

[Files]
Administration=c:\inetpub\wwwroot\emarAPI\pharmacy_notification\pharmacy_notification_administration.txt
Order=c:\inetpub\wwwroot\emarAPI\pharmacy_notification\pharmacy_notification_order.txt

[Actions]
; values match actions table except NewOrder
Order=Modify,NewOrder,OrderDiscontinue
Administration=Hold,Reschedule,UnHold
DeleteNotification=Delete,PharmVerification

[Cart]
Grouped=1

[Exclusions]
Disposition=ED
Frequency=once
