[General]
Cycle=2M
Resend_interval=4H
Subject=[Site.Name]: Emerus eMAR orders requiring verification
; Must separate email recipients with commas since semi-colons are treated as comments
Recipient_31=rrarey@harriscomputer.com
Sender=rrarey@harriscomputer.com
SMTP_server_address=mail.harriscomputer.com
SMTP_server_port=25
SMTP_server_username=
; use base64 encoding for password - originally 'Harris4ever!'
SMTP_server_password=
; Specify whether server uses secure connections [Y/N]
SMTP_server_use_ssl=N

[Files]
Administration=c:\inetpub\wwwroot\emarAPI\pharmacy_notification\pharmacy_notification_administration.txt
Order=c:\inetpub\wwwroot\emarAPI\pharmacy_notification\pharmacy_notification_order.txt

[Actions]
; values match actions table except NewOrder
Order=Modify,NewOrder,OrderDiscontinue
Administration=Hold,Reschedule,UnHold

[Cart]
Grouped=1

[Exclusions]
Disposition=ED
Frequency=once
