import { Patient } from '../interfaces/patient';

export const PATIENTS: Patient[] = [
  {
    id: 1,
    siteId: 2,
    enterprisePatientId: 'P1234',
    medicalRecordNumber: 'M1234',
    accountNumber: 'A1234',
    firstName: 'Franklin',
    lastName: 'Smith',
    middleName: 'Edward',
    nameSuffix: 'Sr.',
    age: 56,
    ageUnits: 'Y',
    gender: 'M',
    complaint: 'Headache',
    dateOfBirth: '1970-05-17',
    roomBedCode: '08',
    wardCode: 'ED',
    departmentCode: 'ED',
    urgency: '02',
    urgencyColor: 'R',
    nameAlert: '1',
    withdrawConsent: '1',
    heightInCm: 187.25,
    weightInKg: 90.71,
    vsDateTime: '2019-10-01T00:00:00',
    vsBloodPressureIndicator: '1',
    vsSystolic: '120',
    vsDiastolic: '80',
    vsPulseIndicator: '1',
    vsPulse: '80',
    vsMapLevel: '0',
    vsMap: '48',
    vsRespiratoryIndicator: '0',
    vsRespiratory: '10',
    vsTemperatureIndicator: '1',
    vsTemperature: '98.6',
    vsEndTidalLevel: '2',
    vsEndTidal: '50',
    vsOxygenSaturationIndicator: '1',
    vsOxygenSaturation: '99 on Room Air',
    vsPainScaleIndicator: '0',
    vsPainScale: '2',
    customIndicators: [
      {
        position: 0,
        code: 'Hero',
        type: 'BAT',
        description: 'JLA ID: Cuz I am Batman',
        imageName: 'batman.gif',
      },
      {
        position: 1,
        code: 'STOP',
        type: 'STOP',
        description: 'Need to Register: Stop',
        imageName: 'stop3.jpg',
      },
    ],
    allergies: [
      {
        name: 'Amoxicillin',
        isActive: 1,
        reaction: 'Rash',
        severity: 'Mild',
        comment: 'Mild Allergy',
        source: '',
      },
      {
        name: 'Pet Dander',
        isActive: 1,
        reaction: 'Sneezing',
        severity: 'Moderate',
        comment: 'Stay away from dander',
        source: '',
      },
      {
        name: 'Dust Mites',
        isActive: 1,
        reaction: 'Runny Nose',
        severity: 'Mild',
        comment: 'Get an allergen filter',
        source: '',
      },
      {
        name: 'Pollen',
        isActive: 1,
        reaction: 'Watery Eyes',
        severity: 'High',
        comment: '',
        source: '',
      },
      {
        name: 'Bee Sting',
        isActive: 1,
        reaction: 'Hives',
        severity: 'Moderate',
        comment: 'Get treatment',
        source: '',
      },
    ],
    homeMeds: [
      {
        name: 'Tylenol',
        isActive: 1,
        dose: '200 MG',
        unit: 'MG',
        route: 'Oral',
        schedule: 'PRN',
        lastTaken: '2020-07-12T14:30:00',
        comment: 'Taken as needed',
      },
      {
        name: 'Motrin',
        isActive: 1,
        dose: '400 MG',
        unit: 'MG',
        route: 'Oral',
        schedule: 'PRN',
        lastTaken: '2020-07-11T08:00:00',
        comment: 'Taken as needed to supplement Tylenol',
      },
      {
        name: 'Azithromycin',
        isActive: 1,
        dose: '500 MG',
        unit: 'MG',
        route: 'Oral',
        schedule: 'Every 8 hours',
        lastTaken: '2020-07-12T19:30:00',
        comment: 'Take every 8 hours',
      },
      {
        name: 'Lisinopril ',
        isActive: 1,
        dose: '20 MG',
        unit: 'MG',
        route: 'Oral',
        schedule: 'Every 6 hours',
        lastTaken: '2020-07-13T07:30:00',
        comment: 'For Hypertension',
      },
      {
        name: 'Crestor',
        isActive: 1,
        dose: '10 MG',
        unit: 'MG',
        route: 'Oral',
        schedule: 'Every 12 hours',
        lastTaken: '2020-07-12T18:00:00',
        comment: 'For Cholesterol Management and Monitoring',
      },
    ],
  },
];
